# Generated by Django 2.2.6 on 2019-11-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_areainfo_employeebasicinfo_employeedetailinfo_newsinfo_newstype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
